### ISSUE TITLE
ModuleNotFoundError: No module named 'datapaths'

### ISSUE THREAD

**Issue by LeeWise9** [resistics/resistics#11]
```
from datapaths import projectPath, imagePath
from resistics.project.io import loadProject

# load the project
projData = loadProject(projectPath)

# load the viewing method
from resistics.project.time import viewTime

# view data between certain date range
fig = viewTime(
    projData, "2012-02-11 01:00:00", "2012-02-11 01:10:00", show=False, save=False
)
fig.savefig(imagePath / "viewTime_projtime_view")


>>> ModuleNotFoundError: No module named 'datapaths'
```

**Comment by nss350** [comment]
Hi there, for my examples, I keep the datapaths in a separate file. It's a Python file with the path to my project and where I would like to save images. Please scroll down to the note on this page of the documentation:
https://resistics.io/tutorial.html

For example, my datapaths.py file looks like:

```python
from pathlib import Path

datapath = Path("E:/", "magnetotellurics", "code", "resisticsdata", "tutorial")
projectPath = datapath / "tutorialProject"
imagePath = Path("images")

# doc paths
docPath = Path("..", "..", "docs", "source", "_static", "examples", "tutorial")
```

Let me know if you are still struggling with this. Thanks.

**Comment by nss350** [comment]
Just to update this further, you don't need to have a separate datapaths file. However, it helps me manage my projects and the images I produce for resistics documentation. @LeeWise9, could you let me know if the explanation makes sense and I shall close the issue.

**Comment by LeeWise9** [comment]
Thank you very much. This problem has been solved.

**Comment by nss350** [comment]
Great!. Closing.
