### ISSUE TITLE
calculateSpectra errors for files with different days

### ISSUE THREAD

**Issue by andieie** [resistics/resistics#15]
Greetings,

I am having trouble calculating the spectra for data that was acquired overnight. The other test data acquired on the same date with 1-2 hours duration have no problem. I have looked into `reader.py` to identify where it misses the dates but haven’t had any luck in fixing it. Below is the ProjectData printout where you can see that it starts at 17:50 of the previous day. Below is the error message when I execute the following line:
 
executed:
`calculateSpectra(projData)`
 
 error:
```
ValueError: mmap length is greater than file size
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-2565847fb881> in <module>
      1 from resistics.project.spectra import calculateSpectra
      2
----> 3 calculateSpectra(projData)
      4 #calculateSpectra(projData, sites=['eifel'], sampleFreqs=[4096])
      5 projData.refresh()
 
~/.local/lib/python3.8/site-packages/resistics/project/spectra.py in calculateSpectra(projData, **kwargs)
    160                     else reader.getChannels()
    161                 )
--> 162                 timeData = reader.getPhysicalData(startTime, stopTime, chans=dataChans)
    163                 timeData.addComment(breakComment())
    164                 timeData.addComment("Calculating project spectra")
 
~/.local/lib/python3.8/site-packages/resistics/time/reader.py in getPhysicalData(self, startTime, endTime, **kwargs)
    837         options.pop("startSample")
    838         options.pop("endSample")
--> 839         return self.getPhysicalSamples(
    840             startSample=startSample, endSample=endSample, **options
    841         )
 
~/.local/lib/python3.8/site-packages/resistics/time/reader.py in getPhysicalSamples(self, **kwargs)
    747         """
    748         options = self.parseGetDataKeywords(kwargs)
--> 749         timeData = self.getUnscaledSamples(
    750             chans=options["chans"],
    751             startSample=options["startSample"],
 
~/.local/lib/python3.8/site-packages/resistics/time/reader.py in getUnscaledSamples(self, **kwargs)
    637                 )
    638             else:
--> 639                 data[chan] = np.memmap(
    640                     dFile, dtype="int32", mode="r", offset=byteOff, shape=(dSamples)
    641                 )
 
/opt/anaconda3/envs/absub/lib/python3.8/site-packages/numpy/core/memmap.py in __new__(subtype, filename, dtype, mode, offset, shape, order)
    262             bytes -= start
    263             array_offset = offset - start
--> 264             mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
    265
    266             self = ndarray.__new__(subtype, shape, dtype=descr, buffer=mm,
 
ValueError: mmap length is greater than file size`
```
 
Project info : 
12:12:51 ProjectData: ####################
12:12:51 ProjectData: PROJECTDATA INFO BEGIN
12:12:51 ProjectData: ####################
12:12:51 ProjectData: Time data path = mt_playroom/MT_Proc/timeData
12:12:51 ProjectData: Spectra data path = mt_playroom/MT_Proc/specData
12:12:51 ProjectData: Statistics data path = mt_playroom/MT_Proc/statData
12:12:51 ProjectData: Mask data path = mt_playroom/MT_Proc/maskData
12:12:51 ProjectData: TransFunc data path = mt_playroom/MT_Proc/transFuncData
12:12:51 ProjectData: Calibration data path = mt_playroom/MT_Proc/calData
12:12:51 ProjectData: Images data path = mt_playroom/MT_Proc/images
12:12:51 ProjectData: Reference time = 2021-09-29 00:00:00
12:12:51 ProjectData: Project start time = 2021-09-29 17:50:00.000000
12:12:51 ProjectData: Project stop time = 2021-09-30 09:19:14.425781
12:12:51 ProjectData: Project found 1 sites:
12:12:51 ProjectData: eifel_overnight                                      start: 2021-09-29 17:50:00              end: 2021-09-30 09:19:14.425781
12:12:51 ProjectData: Sampling frequencies found in project (Hz): 256.0
12:12:51 ProjectData: ####################
12:12:51 ProjectData: PROJECTDATA INFO END
12:12:51 ProjectData: ####################
 
I would really appreciate some help. Thank you in advance.

**Comment by nss350** [comment]
Hmm, interesting. It looks like the time data file is smaller than expected and when it tries to read it, it's going past the end of the file. Can you tell me the size of the file and the number of samples you expect in the file? There's a chance we can read it by changing some information in the XML file (if this is ATS data).

**Comment by andieie** [comment]
Sorry for the late reply.  Yes this is ATS data. The size of the file is : 241 kb. and the number of samples in the file is : 14273134. Although if I calculate number of seconds with the frequency (256) I get 14273024. Here are the first 40 lines of the XML file 
```
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<measurement>
  <recording>
    <start_time>17:50:00</start_time>
    <stop_time>09:19:14</stop_time>
    <start_date>2021-09-29</start_date>
    <stop_date>2021-09-30</stop_date>
    <target_directory>/mtdata/data</target_directory>
    <CyclicEvent>0</CyclicEvent>
    <Cycle>60</Cycle>
    <Granularity>seconds</Granularity>
    <input>
      <Hardware Name="ADU-08e" GMS="8" Type="1">
        <global_config>
          <meas_channels>5</meas_channels>
          <sample_freq>256</sample_freq>
          <buffer>16384</buffer>
          <start_stop_mode>1</start_stop_mode>
          <calon>0</calon>
          <atton>0</atton>
          <calref>0</calref>
          <calint>0</calint>
          <calfreq>16384.0</calfreq>
          <short_circuit>0</short_circuit>
          <decimation>0</decimation>
          <flush_fill>64</flush_fill>
          <ovl_fill>1024</ovl_fill>
          <start_stop_fill>512</start_stop_fill>
        </global_config>
        <channel_config>
          <channel id="0">
            <gain_stage1>4</gain_stage1>
            <gain_stage2>1</gain_stage2>
            <ext_gain>1</ext_gain>
            <filter_type>LF_RF_2</filter_type>
            <hchopper>0</hchopper>
            <echopper>0</echopper>
            <dac_val>0</dac_val>
            <dac_on>0</dac_on>
            <input>0</input>
```
Thank you for your help.

**Comment by nss350** [comment]
Usually a single value is 4 bytes in an ATS. 
14273134 samples should give 14273134 * 4 bytes. 
I think ATS files have one data file per channel. So each data file should be 14273134 * 4 bytes in size
14273134 * 4 = 57,092,536 bytes
= 55, 754 kb
= 54mb
Doing some quick maths. 241kb sounds quite small for sampling at 256 Hz. Are you able to check the size of the data files on the machine?

This is off the top of my head so I might be wrong...

**Comment by andieie** [comment]
Sorry I thought you meant the size of the XML. The size of each ATS file is 57 mb.

**Comment by andieie** [comment]
Hello, I solved this issue by going back to another raw XML file. It looks like the data transfer had generated two different ones. Thank you for your help, I will close this now.
