### ISSUE TITLE
I couldn't find the resistics 1.0 in PIPY and how can I install it?

### ISSUE THREAD

**Issue by wsheat** [resistics/resistics#17]
![image](https://user-images.githubusercontent.com/96280690/146496998-e196a8ca-5c4e-4114-ae3b-e2d9643a023c.png)
![image](https://user-images.githubusercontent.com/96280690/146497030-a82b99c7-850b-4b48-8bf4-bb90815e632d.png)

**Comment by wsheat** [comment]
I've found out the way to install the newest resistics and resistics-reader by downloading them in github and install them loaclly in the local catalogue. And I'm wondering whether we should use the resistics-reader  with resistics-1.0?

**Comment by wsheat** [comment]
I've found out the way to install the newest resistics and resistics-reader by downloading them in github and install them loaclly in the local catalogue. And I'm wondering whether we should use the resistics-reader  with resistics-1.0?

**Comment by nss350** [comment]
Hi,
If you go to PYPI, you can see the command to use to install a particular version (including pre-releases).
https://pypi.org/project/resistics/1.0.0a3/
There is a release history on the left hand side which shows all versions. By default, pypi installs the last stable version, which was version 0.0.6 as resistics 1.0.0 is still pre-release (there are a few bugs that I need to iron out).

The resistics-readers package should be used with 1.0.0a3.
https://pypi.org/project/resistics-readers/

I will close for now, but reopen if you continue to have issues.
