### ISSUE TITLE
No 'datapaths' module

### ISSUE THREAD

**Issue by forrest-gang** [resistics/resistics#28]
Hi, 
I am very intersted in MT data processing, and I find 'resistics' must a nice tools to handle the MT time series data.
I tested the resistics code follow the steps as the tutorial, but at the first step I get the trouble, 
the code is:
from datapaths import projectPath, imagePath
from resistics.project.io import newProject
# # define reference time for project
referenceTime = "2012-02-10 00:00:00"
# #create a new project and print infomation
projData = newProject(projectPath, reference
projData.printInfo()

the compiler show: 
ModuleNotFoundError: No module named 'datapaths'
![figure](https://user-images.githubusercontent.com/67218929/224279897-d21ea11f-402c-4d51-93fa-f25775b7e2f2.png)

**Comment by forrest-gang** [comment]
I mainly use the resistics for remote reference processing. Since I know that version 1.0.0 cannot be used for remote reference at present, I can only use version 0.0.6 for now.

**Comment by nss350** [comment]
Hi there and sorry for the delay. The datapaths module I have is just a place where I store all the paths to where things are on disk. You can delete that import and just define projectPath as the location of your project on disk. Hope that helps.

**Comment by nss350** [comment]
Closing as no further response, hopefully the issue was resolved.
